version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - CONN_STRING=your_connection_string
      - ASSEMBLYAI_API_KEY=your_api_key
      - DEEPL_API_KEY=your_api_key
    volumes:
      - videos:~/Desktop
    depends_on:
      - ffmpeg
  ffmpeg:
    image: jrottenberg/ffmpeg:latest

  